[package]
name = "xv7-usyscall"
version = "0.1.0"
authors = ["imtsuki <me@qjx.app>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
